name: Deploy on server

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy-on-server:
    runs-on: ubuntu-latest
    steps:
      - name: Generate version from timestamp
        id: step_one
        run: echo "imageVersion=$(date +'%Y%m%d%H%M')" >> "$GITHUB_ENV"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and save image
        run: |
          docker build -t board-game:$imageVersion .
          docker save board-game:$imageVersion  -o board-game$imageVersion.tar

      - name: Transfer image to server
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ secrets.SERVER_URL  }}
          USER: ${{ secrets.SERVER_SSH_USER  }}
          PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD  }}
          PORT: ${{ secrets.SERVER_SSH_PORT  }}
          SOURCE: board-game$imageVersion.tar
          TARGET: ${{ secrets.SERVER_TARGET  }}
          ARGS_MORE: -avP --partial --progress

      - name: delete previous image, load and run new image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_URL  }}
          username: ${{ secrets.SERVER_SSH_USER  }}
          password: ${{ secrets.SERVER_SSH_PASSWORD  }}
          port: ${{ secrets.SERVER_SSH_PORT  }}
          script: |
            cd ${{ secrets.SERVER_TARGET  }}
            # Stop and remove the existing container on port 8080, 8081
            docker rm -f board-game > /dev/null 2>&1
            docker load <  board-game${{ env.imageVersion }}.tar
            docker  run --name  board-game -p 9090:8083 --add-host=mysql-server:172.17.0.1   -e DB_PASSWORD=${{ secrets.DB_PASSWORD  }}  -e DB_USERNAME=${{ secrets.DB_USERNAME  }} -e DB_NAME=${{ secrets.DB_NAME  }} -e "SPRING_PROFILES_ACTIVE=prod"    -d board-game:${{ env.imageVersion }}
